### ISSUE TITLE
split test project & unit test coverage

### ISSUE THREAD

**Issue by nickChenyx** [alexRyccc/weed#4]
test 文件路径需要从项目源路径中分离出，并构造对应的单测，完成项目测试覆盖率指标展示。

**Comment by nickChenyx** [comment]
作者可以安排完成这个单测么，这样使用者可以更方便的查看项目的单测覆盖率，也可以方便后续迭代时能覆盖新的 case。项目结构也会更清晰，单测代码不会打包到发布版本中。

**Comment by alexRyccc** [comment]
好的，谢谢，我这边来整理一下

**Comment by nickChenyx** [comment]
好的，完成了你可以关闭这个 issue 哈。

**Comment by alexRyccc** [comment]
好的谢谢大佬
