### ISSUE TITLE
unify code style

### ISSUE THREAD

**Issue by nickChenyx** [alexRyccc/weed#5]
代码风格不统一，缩进空行等比较混乱，建议使用 [google code style](https://google.github.io/styleguide/javaguide.html) 或者 [alibaba code style](https://github.com/alibaba/p3c) 统一格式化，并作为 pr 的统一代码格式化需要。

**Comment by alexRyccc** [comment]
好的，因为之前直接是用的java包的模式，现在再转化为maven类型，然后去重新整理格式

**Comment by nickChenyx** [comment]
好的，完成了你可以关闭这个 issue 哈。
